shared:
    priority_rules: &priority_rules
        - name: hotfix PR detected
          conditions:
            - label=hotfix
          priority: high
        - name: lowprio PR detected
          conditions:
            - label=lowprio
          priority: low

    CheckRuns: &CheckRuns
      - or:
        - and:
          - queue-partition-name=rush
          - "check-success=CI / Node.js v14 (ubuntu-latest) (pull_request)"
          - "check-success=CI / Node.js v18 (ubuntu-latest) (pull_request)"
          - "check-success=CI / Node.js v16 (windows-latest) (pull_request)"
          - "check-success=CI / Node.js v18 (windows-latest) (pull_request)"
          - "check-success=license/cla"
        - and:
          - queue-partition-name=heft
          - "check-success=CI / Node.js v14 (ubuntu-latest) (pull_request)"
          - "check-success=CI / Node.js v18 (ubuntu-latest) (pull_request)"
          - "check-success=CI / Node.js v16 (windows-latest) (pull_request)"
          - "check-success=CI / Node.js v18 (windows-latest) (pull_request)"
          - "check-success=license/cla"
        - and:
          - queue-partition-name=rundown
          - "check-success=CI / Node.js v14 (ubuntu-latest) (pull_request)"
          - "check-success=CI / Node.js v18 (ubuntu-latest) (pull_request)"
          - "check-success=CI / Node.js v16 (windows-latest) (pull_request)"
          - "check-success=CI / Node.js v18 (windows-latest) (pull_request)"
          - "check-success=license/cla"

pull_request_rules:
   - name: queue PR with queue label
     conditions:
       - label=queue
     actions:
       queue:

   - name: request review from Pete
     conditions:
       - -author=octogonz
       - -merged
       - -closed
     actions:
       request_reviews:
         users:
           - octogonz

   - name: testing requirements
     conditions:
         - or:
           - label=skip tests
           - "-title~=^(feat|fix)"
           - "files~=rushstack-mergify/build-tests"
     actions:
       post_check:
         title: |
           {% if check_succeed %}
           Testing requirements are present.
           {% else %}
           Testing requirements are missing.
           {% endif %}


partition_rules:
  - name: rush
    conditions:
      - files~=^apps/rush

  - name: heft
    conditions:
      - files~=^apps/heft

  - name: rundown
    conditions:
      - files~=^apps/rundown


queue_rules:
  - name: hotfix
    priority_rules: *priority_rules
    queue_conditions:
      - label=hotfix
    merge_conditions:
      - and: *CheckRuns

  - name: default
    priority_rules: *priority_rules
    merge_conditions:
      - and: *CheckRuns